<?php

/**
 * @file custom_module.module
 * Short file description here.
 *
 * Long description here.
 */

/**
 * Implements hook_menu().
 */
function my_module_menu() {

  $items['example'] = array(
    'title' => 'Example Page',
    'page callback' => 'example_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function custom_module_help($path, $arg) {

  switch ($path) {
    case 'admin/help#custom_module':

      // Return a line-break version of the README.
      $readme = file_get_contents(drupal_get_path('module', 'custom_module') . '/README.txt');
      return nl2br($readme);
  }
}
